// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: datatypes.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface AttributeHandleSetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.AttributeHandleSet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeHandle attributeHandle = 1;</code>
   */
  java.util.List<hla.rti1516_2024.fedpro.AttributeHandle> 
      getAttributeHandleList();
  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeHandle attributeHandle = 1;</code>
   */
  hla.rti1516_2024.fedpro.AttributeHandle getAttributeHandle(int index);
  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeHandle attributeHandle = 1;</code>
   */
  int getAttributeHandleCount();
  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeHandle attributeHandle = 1;</code>
   */
  java.util.List<? extends hla.rti1516_2024.fedpro.AttributeHandleOrBuilder> 
      getAttributeHandleOrBuilderList();
  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeHandle attributeHandle = 1;</code>
   */
  hla.rti1516_2024.fedpro.AttributeHandleOrBuilder getAttributeHandleOrBuilder(
      int index);
}
