// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface AttributeOwnershipDivestitureIfWantedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.AttributeOwnershipDivestitureIfWantedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.AttributeHandleSet result = 1;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <code>.rti1516_2024.fedpro.AttributeHandleSet result = 1;</code>
   * @return The result.
   */
  hla.rti1516_2024.fedpro.AttributeHandleSet getResult();
  /**
   * <code>.rti1516_2024.fedpro.AttributeHandleSet result = 1;</code>
   */
  hla.rti1516_2024.fedpro.AttributeHandleSetOrBuilder getResultOrBuilder();
}
