// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: datatypes.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface AttributeSetRegionSetPairListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.AttributeSetRegionSetPairList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeSetRegionSetPair AttributeSetRegionSetPair = 1;</code>
   */
  java.util.List<hla.rti1516_2024.fedpro.AttributeSetRegionSetPair> 
      getAttributeSetRegionSetPairList();
  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeSetRegionSetPair AttributeSetRegionSetPair = 1;</code>
   */
  hla.rti1516_2024.fedpro.AttributeSetRegionSetPair getAttributeSetRegionSetPair(int index);
  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeSetRegionSetPair AttributeSetRegionSetPair = 1;</code>
   */
  int getAttributeSetRegionSetPairCount();
  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeSetRegionSetPair AttributeSetRegionSetPair = 1;</code>
   */
  java.util.List<? extends hla.rti1516_2024.fedpro.AttributeSetRegionSetPairOrBuilder> 
      getAttributeSetRegionSetPairOrBuilderList();
  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeSetRegionSetPair AttributeSetRegionSetPair = 1;</code>
   */
  hla.rti1516_2024.fedpro.AttributeSetRegionSetPairOrBuilder getAttributeSetRegionSetPairOrBuilder(
      int index);
}
