// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: datatypes.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface AttributeHandleValueMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.AttributeHandleValueMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
   */
  java.util.List<hla.rti1516_2024.fedpro.AttributeHandleValue> 
      getAttributeHandleValueList();
  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
   */
  hla.rti1516_2024.fedpro.AttributeHandleValue getAttributeHandleValue(int index);
  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
   */
  int getAttributeHandleValueCount();
  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
   */
  java.util.List<? extends hla.rti1516_2024.fedpro.AttributeHandleValueOrBuilder> 
      getAttributeHandleValueOrBuilderList();
  /**
   * <code>repeated .rti1516_2024.fedpro.AttributeHandleValue attributeHandleValue = 1;</code>
   */
  hla.rti1516_2024.fedpro.AttributeHandleValueOrBuilder getAttributeHandleValueOrBuilder(
      int index);
}
