// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface ConnectWithConfigurationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.ConnectWithConfigurationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.RtiConfiguration rtiConfiguration = 1;</code>
   * @return Whether the rtiConfiguration field is set.
   */
  boolean hasRtiConfiguration();
  /**
   * <code>.rti1516_2024.fedpro.RtiConfiguration rtiConfiguration = 1;</code>
   * @return The rtiConfiguration.
   */
  hla.rti1516_2024.fedpro.RtiConfiguration getRtiConfiguration();
  /**
   * <code>.rti1516_2024.fedpro.RtiConfiguration rtiConfiguration = 1;</code>
   */
  hla.rti1516_2024.fedpro.RtiConfigurationOrBuilder getRtiConfigurationOrBuilder();
}
