// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: datatypes.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface ConveyedRegionSetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.ConveyedRegionSet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rti1516_2024.fedpro.ConveyedRegion conveyedRegions = 1;</code>
   */
  java.util.List<hla.rti1516_2024.fedpro.ConveyedRegion> 
      getConveyedRegionsList();
  /**
   * <code>repeated .rti1516_2024.fedpro.ConveyedRegion conveyedRegions = 1;</code>
   */
  hla.rti1516_2024.fedpro.ConveyedRegion getConveyedRegions(int index);
  /**
   * <code>repeated .rti1516_2024.fedpro.ConveyedRegion conveyedRegions = 1;</code>
   */
  int getConveyedRegionsCount();
  /**
   * <code>repeated .rti1516_2024.fedpro.ConveyedRegion conveyedRegions = 1;</code>
   */
  java.util.List<? extends hla.rti1516_2024.fedpro.ConveyedRegionOrBuilder> 
      getConveyedRegionsOrBuilderList();
  /**
   * <code>repeated .rti1516_2024.fedpro.ConveyedRegion conveyedRegions = 1;</code>
   */
  hla.rti1516_2024.fedpro.ConveyedRegionOrBuilder getConveyedRegionsOrBuilder(
      int index);
}
