// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface CreateFederationExecutionWithMIMRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.CreateFederationExecutionWithMIMRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string federationName = 1;</code>
   * @return The federationName.
   */
  java.lang.String getFederationName();
  /**
   * <code>string federationName = 1;</code>
   * @return The bytes for federationName.
   */
  com.google.protobuf.ByteString
      getFederationNameBytes();

  /**
   * <code>.rti1516_2024.fedpro.FomModuleSet fomModules = 2;</code>
   * @return Whether the fomModules field is set.
   */
  boolean hasFomModules();
  /**
   * <code>.rti1516_2024.fedpro.FomModuleSet fomModules = 2;</code>
   * @return The fomModules.
   */
  hla.rti1516_2024.fedpro.FomModuleSet getFomModules();
  /**
   * <code>.rti1516_2024.fedpro.FomModuleSet fomModules = 2;</code>
   */
  hla.rti1516_2024.fedpro.FomModuleSetOrBuilder getFomModulesOrBuilder();

  /**
   * <code>.rti1516_2024.fedpro.FomModule mimModule = 3;</code>
   * @return Whether the mimModule field is set.
   */
  boolean hasMimModule();
  /**
   * <code>.rti1516_2024.fedpro.FomModule mimModule = 3;</code>
   * @return The mimModule.
   */
  hla.rti1516_2024.fedpro.FomModule getMimModule();
  /**
   * <code>.rti1516_2024.fedpro.FomModule mimModule = 3;</code>
   */
  hla.rti1516_2024.fedpro.FomModuleOrBuilder getMimModuleOrBuilder();
}
