// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FederateAmbassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface FederationNotSavedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.FederationNotSaved)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.SaveFailureReason reason = 1;</code>
   * @return The enum numeric value on the wire for reason.
   */
  int getReasonValue();
  /**
   * <code>.rti1516_2024.fedpro.SaveFailureReason reason = 1;</code>
   * @return The reason.
   */
  hla.rti1516_2024.fedpro.SaveFailureReason getReason();
}
