// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FederateAmbassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface FederateResignedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.FederateResigned)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reasonForResignDescription = 1;</code>
   * @return The reasonForResignDescription.
   */
  java.lang.String getReasonForResignDescription();
  /**
   * <code>string reasonForResignDescription = 1;</code>
   * @return The bytes for reasonForResignDescription.
   */
  com.google.protobuf.ByteString
      getReasonForResignDescriptionBytes();
}
