// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: datatypes.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface FederationExecutionInformationSetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.FederationExecutionInformationSet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rti1516_2024.fedpro.FederationExecutionInformation federationExecutionInformation = 1;</code>
   */
  java.util.List<hla.rti1516_2024.fedpro.FederationExecutionInformation> 
      getFederationExecutionInformationList();
  /**
   * <code>repeated .rti1516_2024.fedpro.FederationExecutionInformation federationExecutionInformation = 1;</code>
   */
  hla.rti1516_2024.fedpro.FederationExecutionInformation getFederationExecutionInformation(int index);
  /**
   * <code>repeated .rti1516_2024.fedpro.FederationExecutionInformation federationExecutionInformation = 1;</code>
   */
  int getFederationExecutionInformationCount();
  /**
   * <code>repeated .rti1516_2024.fedpro.FederationExecutionInformation federationExecutionInformation = 1;</code>
   */
  java.util.List<? extends hla.rti1516_2024.fedpro.FederationExecutionInformationOrBuilder> 
      getFederationExecutionInformationOrBuilderList();
  /**
   * <code>repeated .rti1516_2024.fedpro.FederationExecutionInformation federationExecutionInformation = 1;</code>
   */
  hla.rti1516_2024.fedpro.FederationExecutionInformationOrBuilder getFederationExecutionInformationOrBuilder(
      int index);
}
