// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: datatypes.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface FederateHandleSaveStatusPairArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.FederateHandleSaveStatusPairArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rti1516_2024.fedpro.FederateHandleSaveStatusPair federateHandleSaveStatusPair = 1;</code>
   */
  java.util.List<hla.rti1516_2024.fedpro.FederateHandleSaveStatusPair> 
      getFederateHandleSaveStatusPairList();
  /**
   * <code>repeated .rti1516_2024.fedpro.FederateHandleSaveStatusPair federateHandleSaveStatusPair = 1;</code>
   */
  hla.rti1516_2024.fedpro.FederateHandleSaveStatusPair getFederateHandleSaveStatusPair(int index);
  /**
   * <code>repeated .rti1516_2024.fedpro.FederateHandleSaveStatusPair federateHandleSaveStatusPair = 1;</code>
   */
  int getFederateHandleSaveStatusPairCount();
  /**
   * <code>repeated .rti1516_2024.fedpro.FederateHandleSaveStatusPair federateHandleSaveStatusPair = 1;</code>
   */
  java.util.List<? extends hla.rti1516_2024.fedpro.FederateHandleSaveStatusPairOrBuilder> 
      getFederateHandleSaveStatusPairOrBuilderList();
  /**
   * <code>repeated .rti1516_2024.fedpro.FederateHandleSaveStatusPair federateHandleSaveStatusPair = 1;</code>
   */
  hla.rti1516_2024.fedpro.FederateHandleSaveStatusPairOrBuilder getFederateHandleSaveStatusPairOrBuilder(
      int index);
}
