// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: datatypes.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface FederateHandleSetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.FederateHandleSet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rti1516_2024.fedpro.FederateHandle federateHandle = 1;</code>
   */
  java.util.List<hla.rti1516_2024.fedpro.FederateHandle> 
      getFederateHandleList();
  /**
   * <code>repeated .rti1516_2024.fedpro.FederateHandle federateHandle = 1;</code>
   */
  hla.rti1516_2024.fedpro.FederateHandle getFederateHandle(int index);
  /**
   * <code>repeated .rti1516_2024.fedpro.FederateHandle federateHandle = 1;</code>
   */
  int getFederateHandleCount();
  /**
   * <code>repeated .rti1516_2024.fedpro.FederateHandle federateHandle = 1;</code>
   */
  java.util.List<? extends hla.rti1516_2024.fedpro.FederateHandleOrBuilder> 
      getFederateHandleOrBuilderList();
  /**
   * <code>repeated .rti1516_2024.fedpro.FederateHandle federateHandle = 1;</code>
   */
  hla.rti1516_2024.fedpro.FederateHandleOrBuilder getFederateHandleOrBuilder(
      int index);
}
