// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: datatypes.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface FederateRestoreStatusArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.FederateRestoreStatusArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rti1516_2024.fedpro.FederateRestoreStatus federateRestoreStatus = 1;</code>
   */
  java.util.List<hla.rti1516_2024.fedpro.FederateRestoreStatus> 
      getFederateRestoreStatusList();
  /**
   * <code>repeated .rti1516_2024.fedpro.FederateRestoreStatus federateRestoreStatus = 1;</code>
   */
  hla.rti1516_2024.fedpro.FederateRestoreStatus getFederateRestoreStatus(int index);
  /**
   * <code>repeated .rti1516_2024.fedpro.FederateRestoreStatus federateRestoreStatus = 1;</code>
   */
  int getFederateRestoreStatusCount();
  /**
   * <code>repeated .rti1516_2024.fedpro.FederateRestoreStatus federateRestoreStatus = 1;</code>
   */
  java.util.List<? extends hla.rti1516_2024.fedpro.FederateRestoreStatusOrBuilder> 
      getFederateRestoreStatusOrBuilderList();
  /**
   * <code>repeated .rti1516_2024.fedpro.FederateRestoreStatus federateRestoreStatus = 1;</code>
   */
  hla.rti1516_2024.fedpro.FederateRestoreStatusOrBuilder getFederateRestoreStatusOrBuilder(
      int index);
}
