// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FederateAmbassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface FederationRestoredOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.FederationRestored)
    com.google.protobuf.MessageOrBuilder {
}
