// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FederateAmbassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface FederationRestoreStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.FederationRestoreStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.FederateRestoreStatusArray response = 1;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.rti1516_2024.fedpro.FederateRestoreStatusArray response = 1;</code>
   * @return The response.
   */
  hla.rti1516_2024.fedpro.FederateRestoreStatusArray getResponse();
  /**
   * <code>.rti1516_2024.fedpro.FederateRestoreStatusArray response = 1;</code>
   */
  hla.rti1516_2024.fedpro.FederateRestoreStatusArrayOrBuilder getResponseOrBuilder();
}
