// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FederateAmbassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface FlushQueueGrantOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.FlushQueueGrant)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.LogicalTime time = 1;</code>
   * @return Whether the time field is set.
   */
  boolean hasTime();
  /**
   * <code>.rti1516_2024.fedpro.LogicalTime time = 1;</code>
   * @return The time.
   */
  hla.rti1516_2024.fedpro.LogicalTime getTime();
  /**
   * <code>.rti1516_2024.fedpro.LogicalTime time = 1;</code>
   */
  hla.rti1516_2024.fedpro.LogicalTimeOrBuilder getTimeOrBuilder();

  /**
   * <code>.rti1516_2024.fedpro.LogicalTime optimisticTime = 2;</code>
   * @return Whether the optimisticTime field is set.
   */
  boolean hasOptimisticTime();
  /**
   * <code>.rti1516_2024.fedpro.LogicalTime optimisticTime = 2;</code>
   * @return The optimisticTime.
   */
  hla.rti1516_2024.fedpro.LogicalTime getOptimisticTime();
  /**
   * <code>.rti1516_2024.fedpro.LogicalTime optimisticTime = 2;</code>
   */
  hla.rti1516_2024.fedpro.LogicalTimeOrBuilder getOptimisticTimeOrBuilder();
}
