// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: datatypes.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface FomModuleSetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.FomModuleSet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rti1516_2024.fedpro.FomModule fomModule = 1;</code>
   */
  java.util.List<hla.rti1516_2024.fedpro.FomModule> 
      getFomModuleList();
  /**
   * <code>repeated .rti1516_2024.fedpro.FomModule fomModule = 1;</code>
   */
  hla.rti1516_2024.fedpro.FomModule getFomModule(int index);
  /**
   * <code>repeated .rti1516_2024.fedpro.FomModule fomModule = 1;</code>
   */
  int getFomModuleCount();
  /**
   * <code>repeated .rti1516_2024.fedpro.FomModule fomModule = 1;</code>
   */
  java.util.List<? extends hla.rti1516_2024.fedpro.FomModuleOrBuilder> 
      getFomModuleOrBuilderList();
  /**
   * <code>repeated .rti1516_2024.fedpro.FomModule fomModule = 1;</code>
   */
  hla.rti1516_2024.fedpro.FomModuleOrBuilder getFomModuleOrBuilder(
      int index);
}
