// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface GetAutomaticResignDirectiveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.GetAutomaticResignDirectiveResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.ResignAction result = 1;</code>
   * @return The enum numeric value on the wire for result.
   */
  int getResultValue();
  /**
   * <code>.rti1516_2024.fedpro.ResignAction result = 1;</code>
   * @return The result.
   */
  hla.rti1516_2024.fedpro.ResignAction getResult();
}
