// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface GetDimensionNameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.GetDimensionNameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.DimensionHandle dimension = 1;</code>
   * @return Whether the dimension field is set.
   */
  boolean hasDimension();
  /**
   * <code>.rti1516_2024.fedpro.DimensionHandle dimension = 1;</code>
   * @return The dimension.
   */
  hla.rti1516_2024.fedpro.DimensionHandle getDimension();
  /**
   * <code>.rti1516_2024.fedpro.DimensionHandle dimension = 1;</code>
   */
  hla.rti1516_2024.fedpro.DimensionHandleOrBuilder getDimensionOrBuilder();
}
