// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface GetDimensionHandleSetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.GetDimensionHandleSetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.RegionHandle region = 1;</code>
   * @return Whether the region field is set.
   */
  boolean hasRegion();
  /**
   * <code>.rti1516_2024.fedpro.RegionHandle region = 1;</code>
   * @return The region.
   */
  hla.rti1516_2024.fedpro.RegionHandle getRegion();
  /**
   * <code>.rti1516_2024.fedpro.RegionHandle region = 1;</code>
   */
  hla.rti1516_2024.fedpro.RegionHandleOrBuilder getRegionOrBuilder();
}
