// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface GetExceptionReportingSwitchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.GetExceptionReportingSwitchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   * @return The result.
   */
  boolean getResult();
}
