// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface GetInteractionClassHandleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.GetInteractionClassHandleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string interactionClassName = 1;</code>
   * @return The interactionClassName.
   */
  java.lang.String getInteractionClassName();
  /**
   * <code>string interactionClassName = 1;</code>
   * @return The bytes for interactionClassName.
   */
  com.google.protobuf.ByteString
      getInteractionClassNameBytes();
}
