// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface GetObjectClassHandleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.GetObjectClassHandleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string objectClassName = 1;</code>
   * @return The objectClassName.
   */
  java.lang.String getObjectClassName();
  /**
   * <code>string objectClassName = 1;</code>
   * @return The bytes for objectClassName.
   */
  com.google.protobuf.ByteString
      getObjectClassNameBytes();
}
