// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface GetParameterNameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.GetParameterNameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.InteractionClassHandle interactionClass = 1;</code>
   * @return Whether the interactionClass field is set.
   */
  boolean hasInteractionClass();
  /**
   * <code>.rti1516_2024.fedpro.InteractionClassHandle interactionClass = 1;</code>
   * @return The interactionClass.
   */
  hla.rti1516_2024.fedpro.InteractionClassHandle getInteractionClass();
  /**
   * <code>.rti1516_2024.fedpro.InteractionClassHandle interactionClass = 1;</code>
   */
  hla.rti1516_2024.fedpro.InteractionClassHandleOrBuilder getInteractionClassOrBuilder();

  /**
   * <code>.rti1516_2024.fedpro.ParameterHandle parameter = 2;</code>
   * @return Whether the parameter field is set.
   */
  boolean hasParameter();
  /**
   * <code>.rti1516_2024.fedpro.ParameterHandle parameter = 2;</code>
   * @return The parameter.
   */
  hla.rti1516_2024.fedpro.ParameterHandle getParameter();
  /**
   * <code>.rti1516_2024.fedpro.ParameterHandle parameter = 2;</code>
   */
  hla.rti1516_2024.fedpro.ParameterHandleOrBuilder getParameterOrBuilder();
}
