// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface GetTransportationTypeHandleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.GetTransportationTypeHandleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transportationTypeName = 1;</code>
   * @return The transportationTypeName.
   */
  java.lang.String getTransportationTypeName();
  /**
   * <code>string transportationTypeName = 1;</code>
   * @return The bytes for transportationTypeName.
   */
  com.google.protobuf.ByteString
      getTransportationTypeNameBytes();
}
