// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: datatypes.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface JoinResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.JoinResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.FederateHandle federateHandle = 1;</code>
   * @return Whether the federateHandle field is set.
   */
  boolean hasFederateHandle();
  /**
   * <code>.rti1516_2024.fedpro.FederateHandle federateHandle = 1;</code>
   * @return The federateHandle.
   */
  hla.rti1516_2024.fedpro.FederateHandle getFederateHandle();
  /**
   * <code>.rti1516_2024.fedpro.FederateHandle federateHandle = 1;</code>
   */
  hla.rti1516_2024.fedpro.FederateHandleOrBuilder getFederateHandleOrBuilder();

  /**
   * <code>string logicalTimeImplementationName = 2;</code>
   * @return The logicalTimeImplementationName.
   */
  java.lang.String getLogicalTimeImplementationName();
  /**
   * <code>string logicalTimeImplementationName = 2;</code>
   * @return The bytes for logicalTimeImplementationName.
   */
  com.google.protobuf.ByteString
      getLogicalTimeImplementationNameBytes();
}
