// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FederateAmbassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface ObjectInstanceNameReservationFailedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.ObjectInstanceNameReservationFailed)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string objectInstanceName = 1;</code>
   * @return The objectInstanceName.
   */
  java.lang.String getObjectInstanceName();
  /**
   * <code>string objectInstanceName = 1;</code>
   * @return The bytes for objectInstanceName.
   */
  com.google.protobuf.ByteString
      getObjectInstanceNameBytes();
}
