// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface RegisterObjectInstanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.RegisterObjectInstanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.ObjectClassHandle objectClass = 1;</code>
   * @return Whether the objectClass field is set.
   */
  boolean hasObjectClass();
  /**
   * <code>.rti1516_2024.fedpro.ObjectClassHandle objectClass = 1;</code>
   * @return The objectClass.
   */
  hla.rti1516_2024.fedpro.ObjectClassHandle getObjectClass();
  /**
   * <code>.rti1516_2024.fedpro.ObjectClassHandle objectClass = 1;</code>
   */
  hla.rti1516_2024.fedpro.ObjectClassHandleOrBuilder getObjectClassOrBuilder();
}
