// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FederateAmbassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface ReportAttributeTransportationTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.ReportAttributeTransportationType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
   * @return Whether the objectInstance field is set.
   */
  boolean hasObjectInstance();
  /**
   * <code>.rti1516_2024.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
   * @return The objectInstance.
   */
  hla.rti1516_2024.fedpro.ObjectInstanceHandle getObjectInstance();
  /**
   * <code>.rti1516_2024.fedpro.ObjectInstanceHandle objectInstance = 1;</code>
   */
  hla.rti1516_2024.fedpro.ObjectInstanceHandleOrBuilder getObjectInstanceOrBuilder();

  /**
   * <code>.rti1516_2024.fedpro.AttributeHandle attribute = 2;</code>
   * @return Whether the attribute field is set.
   */
  boolean hasAttribute();
  /**
   * <code>.rti1516_2024.fedpro.AttributeHandle attribute = 2;</code>
   * @return The attribute.
   */
  hla.rti1516_2024.fedpro.AttributeHandle getAttribute();
  /**
   * <code>.rti1516_2024.fedpro.AttributeHandle attribute = 2;</code>
   */
  hla.rti1516_2024.fedpro.AttributeHandleOrBuilder getAttributeOrBuilder();

  /**
   * <code>.rti1516_2024.fedpro.TransportationTypeHandle transportationType = 3;</code>
   * @return Whether the transportationType field is set.
   */
  boolean hasTransportationType();
  /**
   * <code>.rti1516_2024.fedpro.TransportationTypeHandle transportationType = 3;</code>
   * @return The transportationType.
   */
  hla.rti1516_2024.fedpro.TransportationTypeHandle getTransportationType();
  /**
   * <code>.rti1516_2024.fedpro.TransportationTypeHandle transportationType = 3;</code>
   */
  hla.rti1516_2024.fedpro.TransportationTypeHandleOrBuilder getTransportationTypeOrBuilder();
}
