// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FederateAmbassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface RequestRetractionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.RequestRetraction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.MessageRetractionHandle retraction = 1;</code>
   * @return Whether the retraction field is set.
   */
  boolean hasRetraction();
  /**
   * <code>.rti1516_2024.fedpro.MessageRetractionHandle retraction = 1;</code>
   * @return The retraction.
   */
  hla.rti1516_2024.fedpro.MessageRetractionHandle getRetraction();
  /**
   * <code>.rti1516_2024.fedpro.MessageRetractionHandle retraction = 1;</code>
   */
  hla.rti1516_2024.fedpro.MessageRetractionHandleOrBuilder getRetractionOrBuilder();
}
