// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface SetRangeBoundsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.SetRangeBoundsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.RegionHandle region = 1;</code>
   * @return Whether the region field is set.
   */
  boolean hasRegion();
  /**
   * <code>.rti1516_2024.fedpro.RegionHandle region = 1;</code>
   * @return The region.
   */
  hla.rti1516_2024.fedpro.RegionHandle getRegion();
  /**
   * <code>.rti1516_2024.fedpro.RegionHandle region = 1;</code>
   */
  hla.rti1516_2024.fedpro.RegionHandleOrBuilder getRegionOrBuilder();

  /**
   * <code>.rti1516_2024.fedpro.DimensionHandle dimension = 2;</code>
   * @return Whether the dimension field is set.
   */
  boolean hasDimension();
  /**
   * <code>.rti1516_2024.fedpro.DimensionHandle dimension = 2;</code>
   * @return The dimension.
   */
  hla.rti1516_2024.fedpro.DimensionHandle getDimension();
  /**
   * <code>.rti1516_2024.fedpro.DimensionHandle dimension = 2;</code>
   */
  hla.rti1516_2024.fedpro.DimensionHandleOrBuilder getDimensionOrBuilder();

  /**
   * <code>.rti1516_2024.fedpro.RangeBounds rangeBounds = 3;</code>
   * @return Whether the rangeBounds field is set.
   */
  boolean hasRangeBounds();
  /**
   * <code>.rti1516_2024.fedpro.RangeBounds rangeBounds = 3;</code>
   * @return The rangeBounds.
   */
  hla.rti1516_2024.fedpro.RangeBounds getRangeBounds();
  /**
   * <code>.rti1516_2024.fedpro.RangeBounds rangeBounds = 3;</code>
   */
  hla.rti1516_2024.fedpro.RangeBoundsOrBuilder getRangeBoundsOrBuilder();
}
