// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RTIambassador.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface SubscribeObjectClassDirectedInteractionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.SubscribeObjectClassDirectedInteractionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.ObjectClassHandle objectClass = 1;</code>
   * @return Whether the objectClass field is set.
   */
  boolean hasObjectClass();
  /**
   * <code>.rti1516_2024.fedpro.ObjectClassHandle objectClass = 1;</code>
   * @return The objectClass.
   */
  hla.rti1516_2024.fedpro.ObjectClassHandle getObjectClass();
  /**
   * <code>.rti1516_2024.fedpro.ObjectClassHandle objectClass = 1;</code>
   */
  hla.rti1516_2024.fedpro.ObjectClassHandleOrBuilder getObjectClassOrBuilder();

  /**
   * <code>.rti1516_2024.fedpro.InteractionClassHandleSet interactionClasses = 2;</code>
   * @return Whether the interactionClasses field is set.
   */
  boolean hasInteractionClasses();
  /**
   * <code>.rti1516_2024.fedpro.InteractionClassHandleSet interactionClasses = 2;</code>
   * @return The interactionClasses.
   */
  hla.rti1516_2024.fedpro.InteractionClassHandleSet getInteractionClasses();
  /**
   * <code>.rti1516_2024.fedpro.InteractionClassHandleSet interactionClasses = 2;</code>
   */
  hla.rti1516_2024.fedpro.InteractionClassHandleSetOrBuilder getInteractionClassesOrBuilder();
}
