// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: datatypes.proto
// Protobuf Java Version: 4.30.1

package hla.rti1516_2024.fedpro;

public interface SupplementalReflectInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rti1516_2024.fedpro.SupplementalReflectInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.rti1516_2024.fedpro.FederateHandle producingFederate = 1;</code>
   * @return Whether the producingFederate field is set.
   */
  boolean hasProducingFederate();
  /**
   * <code>.rti1516_2024.fedpro.FederateHandle producingFederate = 1;</code>
   * @return The producingFederate.
   */
  hla.rti1516_2024.fedpro.FederateHandle getProducingFederate();
  /**
   * <code>.rti1516_2024.fedpro.FederateHandle producingFederate = 1;</code>
   */
  hla.rti1516_2024.fedpro.FederateHandleOrBuilder getProducingFederateOrBuilder();

  /**
   * <code>bool conveyedRegionsIsValid = 2;</code>
   * @return The conveyedRegionsIsValid.
   */
  boolean getConveyedRegionsIsValid();

  /**
   * <pre>
   * optional, only valid if conveyedRegionsIsValid == true
   * </pre>
   *
   * <code>.rti1516_2024.fedpro.ConveyedRegionSet conveyedRegions = 3;</code>
   * @return Whether the conveyedRegions field is set.
   */
  boolean hasConveyedRegions();
  /**
   * <pre>
   * optional, only valid if conveyedRegionsIsValid == true
   * </pre>
   *
   * <code>.rti1516_2024.fedpro.ConveyedRegionSet conveyedRegions = 3;</code>
   * @return The conveyedRegions.
   */
  hla.rti1516_2024.fedpro.ConveyedRegionSet getConveyedRegions();
  /**
   * <pre>
   * optional, only valid if conveyedRegionsIsValid == true
   * </pre>
   *
   * <code>.rti1516_2024.fedpro.ConveyedRegionSet conveyedRegions = 3;</code>
   */
  hla.rti1516_2024.fedpro.ConveyedRegionSetOrBuilder getConveyedRegionsOrBuilder();
}
